### ** 1. In the below elements which of them are values or an expression? eg:- values can be integar or string and expressions will be mathamatical operators.*

*

'hello'

-87.8

-

/

6

values : 'hello' , -87.8, 6


expressions : * , - , /

### **2. What is the difference between string and variable?**

1. String always starts and ends with quotes where as variables don't.

2. String can hold any type of values(numeric, alphabetic, characters) till they're under quotes and variables can hold numeric values only.

### **3. Describe three data types?**

**Three data types are as follow:**

1. int() : int() is a type of data type which can store whole number, positive number, negative number.

2. float() : float() data type also store number but these numbers in float can only be in decimal format.

3. str() : str() data type can hold any type of value whether they are numeric, alphabetic or special character unless or untill they start and end with quotes.

### **4.What is an expression made up of? what do all expression do? **

Expressions is made up of operators and operands(combination of variable and contant)

Expression evaluates a single value

## **5. This assignment statements, like spam = 10. What is the difference between an expression and statement?**

Expression evaluates a single value where as statement does not.

## **6. After running the following code, what does the variable bacon contain?** 

## **bacon = 22**

## **bacon + 1**

In [1]:
bacon = 22
bacon + 1

23

In [2]:
type(bacon)

int

the variable bacon contain the value 23 and data type of bacon is int().

## **7. What should the values of two term be?**

**'spam' + 'spamspam'**

**'spam' * 3**

In [3]:
'spam' + 'spamspam'

'spamspamspam'

In [4]:
'spam' * 3

'spamspamspam'

The values of both terms are as follows:-

1. 'spamspamspam'

2. 'spamspamspam'

## **8. Why is eggs a variable name while 100 is invalid?**

because in python variable names cannot start with numbers.

### **9. What three functions can be used to get the integar, floating-point number, or string version of value?**

integar : int()

floating-point number : float()

string : str()

## **10. Why does this expression cause an error? How can you fix it?**

**'i have eaten' + 99 + 'burritos'**

cause of this error is 99 because it's an int() value. and in python only string can be concatenate with string. integar with string can not.

so the correct way will be changing data type of 99 to string.

In [6]:
'i have eaten ' + str(99) + ' burritos'

'i have eaten 99 burritos'